# app_name will be used for cache naming and other things
app_name: "irondream.herokuapp.com"

iron:
    token: MY IRON.IO TOKEN
    project_id: MY IRON.IO PROJECT ID

email:
    host: smtp.sendgrid.net
    domain: YOUR DOMAIN, eg: yourbiz.com
    port: 587
    username: USERNAME
    password: PASS
    from: ADDRESS MESSAGES WILL BE SENT FROM

